//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestResult
    {
        public System.Guid Id { get; set; }
        public string JYLSH { get; set; }
        public string JYJGBH { get; set; }
        public string JCXDH { get; set; }
        public string JYXM { get; set; }
        public System.DateTime UDP { get; set; }
        public int Satatus { get; set; }
        public string Shape { get; set; }
        public string SideSlide { get; set; }
        public string Speed { get; set; }
        public string Light { get; set; }
        public string Brake { get; set; }
        public string Weigh { get; set; }
        public string Bottom { get; set; }
        public string BoottomInterval { get; set; }
        public string SoundLevel { get; set; }
        public string Power { get; set; }
        public string FuelConsumption { get; set; }
        public string Exhaust { get; set; }
        public string Balancer { get; set; }
    }
}
