//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YZXDMS.SQLServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaceTable
    {
        public int Id { get; set; }
        public string SFZH { get; set; }
        public string NAME { get; set; }
        public string JCZBH { get; set; }
        public string JYLSH { get; set; }
        public string HPHM { get; set; }
        public string HPZL { get; set; }
        public byte[] FEATURES { get; set; }
        public byte[] FACEIMG { get; set; }
        public string JCSJ { get; set; }
    }
}
